# One dark theme
include                 ./theme.conf
# Fonts
font_family             Hasklug Nerd Font Semibold
bold_font               Hasklug Nerd Font Black 
italic_font             Hasklug Nerd Font Semibold Italic
bold_italic_font        Hasklug Nerd Font Black Italic
font_size               14.0

# Misc
strip_trailing_spaces   smart
focus_follows_mouse     yes 
enable_audio_bell       no
hide_window_decorations titlebar-only
dim_opacity             1
macos_option_as_alt     both

# Tab bar
tab_bar_edge            bottom
tab_bar_style           powerline
tab_bar_min_tabs        1
active_tab_foreground   #282c34
active_tab_background   #98c379
inactive_tab_foreground #98c379
inactive_tab_background #282c34

# Layout & Navigation
enabled_layouts         splits

map F7 layout_action rotate
map F6 launch        --location=hsplit
map F5 launch        --location=vsplit

map alt+left  resize_window narrower
map alt+right resize_window wider
map alt+up    resize_window taller
map alt+down  resize_window shorter

map alt+shift+up    move_window up
map alt+shift+left  move_window left
map alt+shift+right move_window right
map alt+shift+down  move_window down

map alt+h neighboring_window left
map alt+l neighboring_window right
map alt+k neighboring_window up
map alt+j neighboring_window down

