# WARNING: Do not edit this file.
# It was generated by processing /Users/glacion/.config/zsh/profile.sh##template

export HOMEBREW_CELLAR="/opt/homebrew/Cellar"
export HOMEBREW_NO_ENV_HINTS=true
export HOMEBREW_PREFIX="/opt/homebrew"
export HOMEBREW_REPOSITORY="/opt/homebrew"
export INFOPATH="/opt/homebrew/share/info:\
${INFOPATH:-}"
export MANPATH="/opt/homebrew/share/man\
${MANPATH+:$MANPATH}:"
export PATH="/opt/homebrew/opt/coreutils/libexec/gnubin:\
/opt/homebrew/bin:\
/opt/homebrew/sbin:\
/opt/homebrew/opt/python@3.12/libexec/bin:\
/opt/homebrew/opt/node@20/bin:\
${PATH+:$PATH}"

export EDITOR=nvim
export GOPATH=$HOME/.local/share/go
export ZGENOM_DIR=$HOME/.local/share/zgenom
