# WARNING: Do not edit this file.
# It was generated by processing /Users/glacion/.config/zsh/profile.sh##template

export HOMEBREW_CELLAR="/opt/homebrew/Cellar"
export HOMEBREW_NO_ENV_HINTS=true
export HOMEBREW_PREFIX="/opt/homebrew"
export HOMEBREW_REPOSITORY="/opt/homebrew"
export INFOPATH="/opt/homebrew/share/info:\
${INFOPATH:-}"
export MANPATH="/opt/homebrew/share/man\
${MANPATH+:$MANPATH}:"
export PATH="$HOME/.config/zsh/bin:\
$HOME/.cargo/bin:\
$HOME/.local/bin:\
/opt/homebrew/opt/coreutils/libexec/gnubin:\
/opt/homebrew/bin:\
/opt/homebrew/sbin:\
${PATH+:$PATH}"

export ZOXIDE_CMD_OVERRIDE=cd
export EDITOR=nvim
export GOPATH=$HOME/.local/share/go
export TERRAFORM_BINARY_NAME=tofu
export ZGENOM_DIR=$HOME/.local/share/zgenom
