black='#1e2127'
black_light='#282c34'
cyan='#56b6c2'
blue='#61afef'
red='#e06c75'
yellow='#d19a66'

typeset -A ZSH_HIGHLIGHT_STYLES
ZSH_HIGHLIGHT_STYLES[comment]='fg=white'

typeset -g POWERLEVEL9K_INSTANT_PROMPT=verbose

typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
    prompt_char
    user
    host
    dir
    vcs
    command_execution_time
    newline
    status
)

typeset -g POWERLEVEL9K_PROMPT_CHAR_BACKGROUND=$yellow
typeset -g POWERLEVEL9K_PROMPT_CHAR_FOREGROUND=$black

typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=()

typeset -g POWERLEVEL9K_MODE=nerdfont-complete

typeset -g POWERLEVEL9K_ICON_PADDING=moderate

typeset -g POWERLEVEL9K_VCS_VISUAL_IDENTIFIER_EXPANSION=
typeset -g POWERLEVEL9K_VCS_BACKGROUND=$yellow
typeset -g POWERLEVEL9K_VCS_FOREGROUND=$black

typeset -g POWERLEVEL9K_USER_BACKGROUND=$black_light
typeset -g POWERLEVEL9K_USER_FOREGROUND=$yellow

typeset -g POWERLEVEL9K_HOST_BACKGROUND=$black_light
typeset -g POWERLEVEL9K_HOST_FOREGROUND=$yellow

typeset -g POWERLEVEL9K_DIR_BACKGROUND=$blue
typeset -g POWERLEVEL9K_DIR_FOREGROUND=$black
typeset -g POWERLEVEL9K_DIR_SHOW_WRITABLE=v3

typeset -g POWERLEVEL9K_STATUS_EXTENDED_STATES=true
typeset -g POWERLEVEL9K_STATUS_OK=true
typeset -g POWERLEVEL9K_STATUS_OK_BACKGROUND=$yellow
typeset -g POWERLEVEL9K_STATUS_OK_FOREGROUND=$black
typeset -g POWERLEVEL9K_STATUS_OK_VISUAL_IDENTIFIER_EXPANSION='✔'

typeset -g POWERLEVEL9K_STATUS_OK_PIPE=true
typeset -g POWERLEVEL9K_STATUS_OK_PIPE_BACKGROUND=$yellow
typeset -g POWERLEVEL9K_STATUS_OK_PIPE_FOREGROUND=$black
typeset -g POWERLEVEL9K_STATUS_OK_PIPE_VISUAL_IDENTIFIER_EXPANSION='✔'

typeset -g POWERLEVEL9K_STATUS_ERROR=true
typeset -g POWERLEVEL9K_STATUS_ERROR_BACKGROUND=$red
typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND=$black
typeset -g POWERLEVEL9K_STATUS_ERROR_VISUAL_IDENTIFIER_EXPANSION='✘'

typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL=true
typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_BACKGROUND=$red
typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_FOREGROUND=$black
typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_VISUAL_IDENTIFIER_EXPANSION='✘'
typeset -g POWERLEVEL9K_STATUS_VERBOSE_SIGNAME=false

typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE=true
typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE_BACKGROUND=$red
typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE_FOREGROUND=$black
typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE_VISUAL_IDENTIFIER_EXPANSION='✘'

typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND=$cyan
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=$black
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=0
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=5

unset black black_light cyan magenta red yellow
