set -g status-right "%H:%M"
set -g window-status-current-style "underscore"
set -g default-terminal "screen-256color"
set -g bell-action none
set -g mouse on

set-option -g focus-events on
set-option -sg escape-time 10
set-option -sa terminal-overrides ",xterm-kitty:RGB"
set-option -g prefix M-`

unbind -n MouseDrag1Pane
unbind -Tcopy-mode MouseDrag1Pane
unbind C-b

bind-key M-` send-prefix

bind -n M-t new-window
bind -n M-\\ next-window
bind -n M-\' previous-window

bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

bind -n M-C-h split -hb
bind -n M-C-j split -v
bind -n M-C-k split -vb
bind -n M-C-l split -h

