typeset -g POWERLEVEL9K_INSTANT_PROMPT=verbose

typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
    user
    host
    dir
    vcs
    command_execution_time
    newline
    status
)

typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=()

typeset -g POWERLEVEL9K_MODE=nerdfont-complete
typeset -g POWERLEVEL9K_ICON_PADDING=moderate

typeset -g POWERLEVEL9K_VCS_VISUAL_IDENTIFIER_EXPANSION=

typeset -g POWERLEVEL9K_DIR_BACKGROUND=4
typeset -g POWERLEVEL9K_DIR_FOREGROUND=254
typeset -g POWERLEVEL9K_DIR_SHOW_WRITABLE=v3

typeset -g POWERLEVEL9K_STATUS_EXTENDED_STATES=true

typeset -g POWERLEVEL9K_STATUS_OK=true
typeset -g POWERLEVEL9K_STATUS_OK_VISUAL_IDENTIFIER_EXPANSION='✔'
typeset -g POWERLEVEL9K_STATUS_OK_FOREGROUND=0
typeset -g POWERLEVEL9K_STATUS_OK_BACKGROUND=3

typeset -g POWERLEVEL9K_STATUS_OK_PIPE=true
typeset -g POWERLEVEL9K_STATUS_OK_PIPE_VISUAL_IDENTIFIER_EXPANSION='✔'
typeset -g POWERLEVEL9K_STATUS_OK_PIPE_FOREGROUND=0
typeset -g POWERLEVEL9K_STATUS_OK_PIPE_BACKGROUND=3

typeset -g POWERLEVEL9K_STATUS_ERROR=true
typeset -g POWERLEVEL9K_STATUS_ERROR_VISUAL_IDENTIFIER_EXPANSION='✘'
typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND=0
typeset -g POWERLEVEL9K_STATUS_ERROR_BACKGROUND=3

typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL=true
typeset -g POWERLEVEL9K_STATUS_VERBOSE_SIGNAME=false
typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_VISUAL_IDENTIFIER_EXPANSION='✘'
typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_FOREGROUND=0
typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_BACKGROUND=3

typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE=true
typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE_VISUAL_IDENTIFIER_EXPANSION='✘'
typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE_FOREGROUND=0
typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE_BACKGROUND=3

typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=0
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND=3
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=5
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=0

